/* eslint-disable @typescript-eslint/no-explicit-any */
import { type NextPage } from "next";
import Head from "next/head";
import Link from "next/link";
import Image from "next/image";
import { useState, useRef } from "react";
import { motion, Variants } from "framer-motion";
import Hero from "@src/components/Hero";
import SelectedWorks from "@src/components/SelectedWorks";
import About from "@src/components/About";

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Fateh Hadjarsi Portfolio</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main
        className="relative min-h-screen w-screen overflow-x-hidden bg-black "
        id="main"
      >
        <Hero />
        <SelectedWorks />
        <About />
      </main>
    </>
  );
};

export default Home;
